services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: idurar

  backend:
    build: ./backend
    ports:
      - "8888:8888"
    depends_on:
      - mongo
    environment:
      DATABASE: mongodb://admin:password@mongo:27017/idurar?authSource=admin
      JWT_SECRET: "your_private_jwt_secret_key"
      NODE_ENV: "production"
      OPENSSL_CONF: "/dev/null"
      PUBLIC_SERVER_FILE: "http://localhost:8888/"
      PORT: 8888

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VITE_FILE_BASE_URL: http://localhost:8888/
      VITE_BACKEND_SERVER: http://localhost:8888/
      PROD: false
